USE [TommiQA1]

GO

CREATE NONCLUSTERED INDEX [NonClusteredIndex-20240229-123053] ON [dbo].[apfx_Address]
(
	[AddressId] ASC
)
INCLUDE([ActiveFlag]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)

GO


