CREATE NONCLUSTERED INDEX [NonClusteredIndex-Case] ON [dbo].[Case]
(
	[Id] ASC
)
INCLUDE([Data_Warehouse_ID__c]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)

GO