USE [TommiQA1]

GO

CREATE NONCLUSTERED INDEX [NC_Interaction_ActiveFlag] ON [dbo].[apfx_Interaction]
(
	[InteractionId] ASC,
	[ConstituentId] ASC
)
INCLUDE([ActiveFlag]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)

GO


