CREATE NONCLUSTERED INDEX [NonClusteredIndex-XRef-SFID] ON [dbo].[XREF_Account_Household]
(
	[SFID] ASC
)
INCLUDE([DWID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)

GO
